name: Build and Push API Image

on:
  push:
    branches:
      - main # Se dispara en cada push a la rama main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Permiso para subir a GHCR

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        # Este paso es necesario para la emulación de ARM64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        # Prepara el constructor avanzado de Docker

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up NuGet credentials
        run: |
          echo "<configuration>
            <packageSources>
              <clear />
              <add key=\"github\" value=\"https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json\" />
              <add key=\"nuget.org\" value=\"https://api.nuget.org/v3/index.json\" protocolVersion=\"3\" />
            </packageSources>
            <packageSourceCredentials>
              <github>
                <add key=\"Username\" value=\"${{ github.actor }}\" />
                <add key=\"ClearTextPassword\" value=\"${{ secrets.ROCK_TOKEN }}\" />
              </github>
            </packageSourceCredentials>
          </configuration>" > nuget.config
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: . # El contexto es la raíz del repo de la API
          push: true
          platforms: linux/arm64 # ¡Construimos para tu Raspberry Pi!
          tags: ghcr.io/rogithub/ro.inventario.api:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BUILDKIT_INLINE_CACHE=1