name: Build and Push API Image

on:
  push:
    branches:
      - main # Se dispara en cada push a la rama main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Permiso para subir a GHCR

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        # Este paso es necesario para la emulación de ARM64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        # Prepara el constructor avanzado de Docker

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: . # El contexto es la raíz del repo de la API
          push: true
          platforms: linux/arm64 # ¡Construimos para tu Raspberry Pi!
          tags: ghcr.io/rogithub/Ro.Inventario.Api:latest